// <auto-generated />
namespace Infrastructure.Logging.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_log_object : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_log_object));
        
        string IMigrationMetadata.Id
        {
            get { return "201807171534133_create_log_object"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
