POST http://{{host}}/token
Content-Type: text/plain

grant_type=password&username={{username}}&password={{password}}

> {%
client.global.set("token", response.body.token_type + " "+ response.body.access_token);
%}
###

POST http://{{host}}/api/Test2
Content-Type: application/json
Authorization: {{token}}

{
  "answers": [
    173,
    174,
    175,
    176,
    177,
    178
  ],
  "name": "test suggested plan",
  "startDate": "2018-08-21",
  "endDate": "2018-08-21",
  "areaId": 2
}

###

GET http://localhost:56288/api/Group/GetLocationSuggestions
Content-Type: application/json
Authorization: {{token}}

###
