// <auto-generated />
namespace Infrastructure.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class formatDay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(formatDay));
        
        string IMigrationMetadata.Id
        {
            get { return "201807220407203_formatDay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
