// <auto-generated />
namespace Infrastructure.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class refreshToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refreshToken));
        
        string IMigrationMetadata.Id
        {
            get { return "201807280417143_refreshToken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
