// <auto-generated />
namespace Infrastructure.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class recreat_Database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recreat_Database));
        
        string IMigrationMetadata.Id
        {
            get { return "201808170910264_recreat_Database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
